#!/usr/bin/env sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# gtk themes and term colorsheme
# xrdb merge ~/.Xresources &

# wm config
bspc config border_width 3
bspc config window_gap 10
bspc config top_padding 24
bspc config split_ratio 0.50

bspc config focus_follows_pointer true

# xrandr --output HDMI-1 --rotate right --left-of DP-0
# bspc wm -O DP-0 HDMI-1
# bspc monitor DP-0 -d 1 2 3 4 5 6
# bspc monitor HDMI-1 -d 7 8 9 0
bspc monitor -d I II III IV V VI VII VIII IX X

# rules
bspc rule -a "Steam" desktop='^5' state=floating
bspc rule -a "Lightcord" desktop='^7'
bspc rule -a "discord" desktop='^7'
bspc rule -a "Spotify" desktop='^8'

# startup
# setxkbmap se &
# ~/scripts/fetchwal.sh && feh ~/Pictures/wallpapers/ --bg-fill && wal -t -s -i ~/Pictures/wallpapers/ -n & # -b 17191e &
# xsetroot -cursor_name left_ptr

unclutter &
# flameshot &
picom --experimental-backends &
dunst &
# setsid kak -d -s misc &

# Colors
# borders
# bspc config focused_border_color "#d0d0d0"
# bspc config normal_border_color "#151515"
