(define-module (home xorg polybar)
  #:use-module (guix gexp)

  #:use-module (gnu services)
  #:use-module (gnu services shepherd)
  #:use-module (gnu services configuration)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)

  #:use-module (rde serializers ini)

  #:use-module ((gnu packages wm) #:select (polybar))
  #:use-module ((gnu packages fonts) #:select (font-sarasa-gothic))

  #:use-module ((home theme) #:prefix theme:))

(define polybar-config
  (serialize-ini-config
   `((bar/main ((width . "100%")
                (font-0 . ,(string-append theme:font ":size=" theme:font-size))
                (foreground . ,theme:fg)
                (background . ,theme:bg)
                (border-top-size . 6)
                (border-top-color . ,theme:bg)
                (border-bottom-size . 6)
                (border-bottom-color . ,theme:bg)
                (underline-size . 2)
                (underline-color . ,theme:accent)
                (module-margin . "6px")
                (scroll-up . "bspwm.prev")
                (scroll-down . "bspwm.next")
                (modules-left . "bspwm")
                (modules-center . "title")
                (modules-right . "network battery memory cpu date")))
     (module/title ((type . "internal/xwindow")
                    (format-background . ,theme:accent)
                    (label-margin . "6px")))
     (module/bspwm ((type . "internal/bspwm")
                    (format-focused-background . ,theme:accent)
                    (label-margin . "6px")))
     (module/network ((type . "internal/network")
                      (interface-type . "wireless")
                      (speed-unit . "")
                      (format-background . ,theme:accent)
                      (label-margin . "6px")))
     (module/battery ((type . "internal/battery")
                      (battery . "BAT0")
                      (adapter . "ADP1")
                      (format-background . ,theme:accent)
                      (label-margin . "6px")))
     (module/memory ((type . "internal/memory")
                     (label . "%gb_used%/%gb_free%")
                     (format-background . ,theme:accent)
                     (label-margin . "6px")))
     (module/cpu ((type . "internal/cpu")
                  (format-background . ,theme:accent)
                  (label-margin . "6px")))
     (module/date ((type . "internal/date")
                   (date . "%d/%m/%Y%")
                   (time . "%H:%M:%S")
                   (label . "%date% %time%")
                   (format-background . ,theme:accent)
                   (label-margin . "6px"))))))

(define-public services
  (list
   (simple-service 'polybar-xdg-config home-xdg-configuration-files-service-type
                   `(("polybar/config.ini" ,(apply mixed-text-file "config.ini" polybar-config))))))
